services:
  cassandra1:
    image: cassandra:4.1
    hostname: cassandra1
    ports:
      - "7000:7000"
      - "9042:9042"
    volumes:
      - cassandra1_data:/var/lib/cassandra
    networks:
      - cassandranet
    environment:
      - CASSANDRA_SEEDS=cassandra1,cassandra2
      - CASSANDRA_CLUSTER_NAME=nbd-cassandra-cluster
      - CASSANDRA_DC=dc1
      - CASSANDRA_RACK=rack1
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
    healthcheck:
      test: [ "CMD-SHELL", "[ $$(nodetool statusgossip) = running ]" ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 120s

  cassandra2:
    image: cassandra:4.1
    hostname: cassandra2
    ports:
      - "7001:7000"
      - "9043:9042"
    volumes:
      - cassandra2_data:/var/lib/cassandra
    networks:
      - cassandranet
    environment:
      - CASSANDRA_SEEDS=cassandra1,cassandra2
      - CASSANDRA_CLUSTER_NAME=nbd-cassandra-cluster
      - CASSANDRA_DC=dc1
      - CASSANDRA_RACK=rack1
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
    depends_on:
      cassandra1:
        condition: service_healthy
    healthcheck:
      test: [ "CMD-SHELL", "[ $$(nodetool statusgossip) = running ]" ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 120s

volumes:
  cassandra1_data:
    driver: local
  cassandra2_data:
    driver: local

networks:
  cassandranet:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.24.0.0/16
