# Konfiguracja połączenia z klastrem Cassandra
cassandra.contact-points=localhost:9042,localhost:9043
cassandra.local-datacenter=dc1
cassandra.keyspace=wypozyczalnia

# Poziomy spójności
cassandra.consistency.read=LOCAL_QUORUM
cassandra.consistency.write=LOCAL_QUORUM

# Replikacja
cassandra.replication.strategy=NetworkTopologyStrategy
cassandra.replication.dc1=2